import { useContext, useEffect } from "react";
import { AllProducts } from "../../components/organisms/ListProduct";
import { AuthContext } from "../../components/contexts/AuthContext";
import { LoadingAllPage } from "../../components/atoms/Loading";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};

const Products = () => {
  const { load, setLoad } = useContext(AuthContext);
  useEffect(() => {
    setLoad(true);
  }, []);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <div className="container mx-auto pb-10">
        <AllProducts />
      </div>
    </>
  );
};

export default Products;
