import { ListProductTop } from "../components/organisms/ProductTop";
import { HaderSection } from "../components/organisms/HaderSection";
import { ListProductHome } from "../components/organisms/ListProduct";
import { LoadingAllPage } from "../components/atoms/Loading";
import { useContext } from "react";
import { AuthContext } from "../components/contexts/AuthContext";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const Home = () => {
  const { load, setLoad } = useContext(AuthContext);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <HaderSection />
      <div className="container mx-auto">
        <div className="my-5 ">
          <img
            src="https://onewaymobile.vn/images/config/artboard-113x_1711767160.webp"
            alt=""
            className="rounded-lg"
          />
        </div>
        <ListProductTop />
        <ListProductHome />
      </div>
    </>
  );
};
export default Home;
