import { useContext, useEffect } from "react";
import { NewsForm } from "../../components/organisms/News";
import { AuthContext } from "../../components/contexts/AuthContext";
import { LoadingAllPage } from "../../components/atoms/Loading";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const NewsPage = () => {
  const { load, setLoad } = useContext(AuthContext);
  useEffect(() => {
    setLoad(true);
  }, []);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <div className="container mx-auto py-10">
        <NewsForm />
      </div>
    </>
  );
};
export default NewsPage;
