import { useContext, useEffect } from "react";
import { NewsDetail } from "../../../components/organisms/NewsDetail";
import { AuthContext } from "../../../components/contexts/AuthContext";
import { LoadingAllPage } from "../../../components/atoms/Loading";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const NewsDetailPage = () => {
  const { load, setLoad } = useContext(AuthContext);
  useEffect(() => {
    setLoad(true);
  }, []);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <div className="container mx-auto py-10">
        <NewsDetail/>
      </div>
    </>
  );
};
export default NewsDetailPage;
